### PR TITLE
Add chinese language

### PR DESCRIPTION
**Pull request by Qeynos**
But it is still not being called.

### CODE REVIEW

**Comment by SabineWren** [comment]
Hi, for this to work, you need to conditionally include the locale:
```
if GetLocale() == "zhCN" then
-- your translations here
end
```

and in the .toc file, extend
```
Locale\enUS.lua
```
like this
```
Locale\enUS.lua
Locale\zhCN.lua
```

**Comment by Qeynos** [comment]
> Hi, for this to work, you need to conditionally include the locale:
> 
> ```
> if GetLocale() == "zhCN" then
> -- your translations here
> end
> ```
> 
> and in the .toc file, extend
> 
> ```
> Locale\enUS.lua
> ```
> 
> like this
> 
> ```
> Locale\enUS.lua
> Locale\zhCN.lua
> ```

Are there any variables that can be used for language file names? Are you planning to implement multi-language functionality?

**Comment by SabineWren** [comment]
I don't know what you mean. The file names are arbitrary since the .toc maps to them, but for consistency they should use locale codes. `GetLocale` is a client API function.

I make no guarantees about supporting non-English locales. You might consider a defining the overrides in a way that won't break from new English keys, such as:

```
QUIVER_T.AutoShot = QUIVER_T.AutoShot or {}
QUIVER_T.AutoShot.BothDirections = "双向"
```

This way new keys would have a fallback English value instead of null referencing.

Maybe another project figured out a better solution.

**Comment by SabineWren** [comment]
> Are you planning to implement multi-language functionality?

Oh, you mean like pfUI? I suppose that would be easier to support than requiring a fully localized client, so I'm okay with that approach.
https://github.com/shagu/pfUI/tree/master/env

**Comment by Qeynos** [comment]
> > Are you planning to implement multi-language functionality?
> 
> Oh, you mean like pfUI? I suppose that would be easier to support than requiring a fully localized client, so I'm okay with that approach. https://github.com/shagu/pfUI/tree/master/env

Yes, thank you for your project.

**Comment by SabineWren** [comment]
Can you merge your latest translation file into my working dev branch?
https://github.com/SabineWren/Quiver/tree/bundle

**Pull request closed without merging**
