### PR TITLE
Added throw, lol

### PR DESCRIPTION
**Pull request by Jan125**
Added throw, roflmao
- Added new console functions:
- - /qqthrow (for Throw weaving)
- - /qqmultithrow (casting Multi-Shot(Rank 1) because only this first rank is compatible with throwing weapons on Turtle-WoW)

### CODE REVIEW

**Comment by SabineWren** [comment]
I've never considered thrown weapons before. They break the range indicator since they don't work with serpent sting, but that's fixable by checking the Throw action instead.

The purpose of no-clip macros is for castable shots to not interrupt Auto Shot. Throw replaces Auto Shot entirely, and it can't clip Auto Shot when it is the auto shot. I don't understand what a no-clipping Throw command would do.

I don't see an issue on the Twow bug tracker about thrown weapons and multi-shot. Is it intended to only work with rank 1 multi-shot? I don't want to add a dedicated rank 1 kludge to Quiver if Twow will patch it to work with other ranks.

**Comment by SabineWren** [comment]
How about exposing the no-clip logic to macros instead? Then it doesn't matter what Turtle does with thrown weapons.
```lua
/script Quiver_Cast_No_Clip("Multi-Shot(Rank 1)");
```

**Comment by Jan125** [comment]
> I've never considered thrown weapons before. They break the range indicator since they don't work with serpent sting, but that's fixable by checking the Throw action instead.
Just a simple question, is rangechecking Auto Shot not possible? Because of it currently being active?
An alternative could also be Scorpid Sting, since that works with everything.

> The purpose of no-clip macros is for castable shots to not interrupt Auto Shot. Throw replaces Auto Shot entirely, and it can't clip Auto Shot when it is the auto shot. I don't understand what a no-clipping Throw command would do.
Wrong.
On Turtle, Auto Shot works with thrown weapons, you can weave Throw in between the shots.
Throw itself has a 0.5s cast time.

> I don't see an issue on the Twow bug tracker about thrown weapons and multi-shot. Is it intended to only work with rank 1 multi-shot? I don't want to add a dedicated rank 1 kludge to Quiver if Twow will patch it to work with other ranks.
It's been this way since over a year, so I suppose so.
The number of hunters using thrown weapons is probably too low for them to bother fixing/unifying the spells.


> How about exposing the no-clip logic to macros instead? Then it doesn't matter what Turtle does with thrown weapons.
> 
> ```lua
> /script Quiver_Cast_No_Clip("Multi-Shot(Rank 1)");
> ```
That'd work as well.

**Comment by SabineWren** [comment]
Reverted the merge for two reasons:
1. From private conversation with Twow devs, a future patch will break this code, so Quiver support for throwing weapons is a dead end effort.
2. This commit expects 'throw' to appear on action bars, otherwise outputting a warning to chat frame. It would take additional code to check that a throwing weapon is equipped and adjust expected spells accordingly.

**Pull request merged**
